name: Build and Publish Docker

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gepha-geo/sqlserver-schema-migrator

jobs:
  ensure-base-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check if base image exists
        run: |
          if docker manifest inspect ghcr.io/gepha-geo/dotnet-runtime-git:9.0 > /dev/null 2>&1; then
            echo "Base image exists"
          else
            echo "Base image not found. Please run base-image workflow first."
            exit 1
          fi

  build-and-push:
    needs: ensure-base-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=1.0.0,enable={{is_default_branch}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
            
      - name: Make package public
        if: github.ref == 'refs/heads/main'
        run: |
          # Make the package public using GitHub API
          echo "Making package public..."
          PACKAGE_NAME="sqlserver-schema-migrator"
          
          # Wait a bit for the package to be fully registered
          sleep 10
          
          # Update package visibility
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/orgs/GEPHA-geo/packages/container/${PACKAGE_NAME}" \
            -d '{"visibility":"public"}' || echo "Failed to make package public - may need manual configuration"

  test-image:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      packages: read
      
    steps:
      - name: Test Docker image
        run: |
          # Test DACPAC Runner (default entrypoint)
          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest --help || echo "Expected usage output"
          
          # Test Exclusion Manager is available
          docker run --rm --entrypoint /usr/local/bin/exclusion-manager \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest --help || echo "Expected usage output"
          
      - name: Check image metadata
        run: |
          docker inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest