name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gepha-geo/sqlserver-schema-migrator

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            
      - name: Build and push Docker image
        run: |
          # Restore dependencies
          dotnet restore
          
          # Get the first tag from metadata (or use 'latest' for main branch)
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            CONTAINER_TAG="latest"
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            CONTAINER_TAG="${{ github.ref_name }}"
          else
            CONTAINER_TAG="pr-${{ github.event.pull_request.number }}"
          fi
          
          # Build and publish container
          dotnet publish SqlServer.Schema.FileSystem.Serializer.Dacpac.Runner \
            --os linux \
            --arch x64 \
            -c Release \
            /t:PublishContainer \
            -p:ContainerRegistry=${{ env.REGISTRY }} \
            -p:ContainerRepository=${{ env.IMAGE_NAME }} \
            -p:ContainerImageTag=${CONTAINER_TAG}
            
      - name: Build and push multi-arch image (main branch only)
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          # Also build for ARM64
          dotnet publish SqlServer.Schema.FileSystem.Serializer.Dacpac.Runner \
            --os linux \
            --arch arm64 \
            -c Release \
            /t:PublishContainer \
            -p:ContainerRegistry=${{ env.REGISTRY }} \
            -p:ContainerRepository=${{ env.IMAGE_NAME }} \
            -p:ContainerImageTag=latest-arm64
            
      - name: Make package public
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          # Make the package public using GitHub API
          echo "Making package public..."
          PACKAGE_NAME="sqlserver-schema-migrator"
          
          # Wait a bit for the package to be fully registered
          sleep 10
          
          # Update package visibility
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/orgs/GEPHA-geo/packages/container/${PACKAGE_NAME}" \
            -d '{"visibility":"public"}' || echo "Failed to make package public - may need manual configuration"

  test-image:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      packages: read
      
    steps:
      - name: Wait for package visibility update
        run: |
          echo "Waiting for package to become public..."
          sleep 30
          
      - name: Test Docker image
        run: |
          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest || echo "Expected usage error"
          
      - name: Check image metadata
        run: |
          docker inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest